# Generated by Django 3.2.16 on 2022-11-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0002_alter_category_c_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_name',
            field=models.CharField(choices=[('Mobiles', 'Mobiles'), ('Laptops', 'Laptops'), ('PowerBank', 'Power Banks'), ('Cameras & Accessories', 'Cameras & Accessories'), ('Headphones & Speakers', 'Headphones & Speakers')], max_length=30),
        ),
    ]
