# Generated by Django 3.2.16 on 2022-11-25 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0003_alter_category_c_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('customer_id', 'product_id')},
        ),
    ]
