# Generated by Django 3.2.16 on 2022-12-01 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_name',)},
        ),
    ]
