# Generated by Django 3.2.16 on 2022-12-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0010_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('customer_id',)},
        ),
    ]
